language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "0.10"
  - "0.12"

sudo: false

branches:
  except:
    - gh-pages

script:
  - npm test --cover

after_script:
  - if [[ `node --version` == *v0.12* ]]; then cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
